/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /confirmEmail
 */
export interface ConfirmEmailRequestBuilder extends BaseRequestBuilder<ConfirmEmailRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     get(requestConfiguration?: RequestConfiguration<ConfirmEmailRequestBuilderGetQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ConfirmEmailRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface ConfirmEmailRequestBuilderGetQueryParameters {
    changedEmail?: string;
    code?: string;
    userId?: string;
}
/**
 * Uri template for the request builder.
 */
export const ConfirmEmailRequestBuilderUriTemplate = "{+baseurl}/confirmEmail?code={code}&userId={userId}{&changedEmail*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const ConfirmEmailRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ConfirmEmailRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
